http:
  - name: Frontend
    url: https://example.com
    interval: 60
    timeout: 5
    method: GET
    headers: 
    expect_status: 200
tcp:
  - name: API
    host: 127.0.0.1
    port: 3000
    interval: 30
    timeout: 10
dns:
  - name: Server
    hostname: example.com
    interval: 300
    record_type: A
    expect_ip: 192.18.1.20
    
