http:
  - name: Frontend
    url: https://example.com
    interval: 60
    method: GET
    headers:
      Content-Type: application/json
      Authorization: Bearer xyz123
    expect_status: 200
tcp:
  - name: API
    host: 127.0.0.1
    port: 3000
    interval: 30
dns:
  - name: Server
    hostname: example.com
    record_type: A
    expect_ip: 192.168.1.20
    dns_server: 8.8.8.8
    
